import os
Import("*")

client_env = extend_env(env, {
	"CPPPATH": [".", Dirs.source_service]
})

client_translation_units = {
	"session": {},
	"net/service_connection": {},
	"net/service_request": {},
	"net/service_response": {},
}

client_platform_translation_units = {
	"linux": {}
}

client_translation_units.update(
	client_platform_translation_units[THIS_PLATFORM]
)

target_objects = list(
	map(lambda u: client_env.SharedObject(u, "%s.cxx" % u),
		client_translation_units
	)
)


shared_library = client_env.SharedLibrary(
	"dblclient-fPIC",
	[target_objects, common_target_objects]
)

static_library = client_env.Library(
	"dblclient",
	[target_objects, common_target_objects]
)

target_shared = client_env.Install(Dirs.lib_destdir, shared_library)
target_static = client_env.Install(Dirs.lib_destdir, static_library)
Return("target_shared", "target_static")
